name: TarzaxVanish
author: Tarzax
version: 1.0.3
api: 4.0.0
main: tarzax\vanish\Main

commands:
  vanish:
    usage: /vanish
    description: "Vanish mod"
    permission: vanish.use

permissions:
  vanish.use:
    default: op
